triple-site-bonus:
  enabled: true
  required-sites: 3
  placeholder-icon: ' ☁ '
  message: '%prefix%&a¡Has votado en los 3 sitios y ganado Fly por 1 hora!'
  commands:
  - voucher give %player% fly_1h 1

storage:
  sqlite-file: data/vvotes.db
  busy-timeout-ms: 5000

timezone: America/Santiago

global:
  broadcast-on-vote: true
  suspicious-window-seconds: 10

services:
  force-player-command:
    40servidoresMC:
      es:
      - mivoto40

goals:
  global-daily:
    '75':
    - crate key giveall fire 1
    '115':
    - crate key giveall insane 1
    '150':
    - crate key giveall legendary 1
    '190':
    - pa pinata start default default
  global-recurring:
    start-after: 190
    every: 25
    commands:
    - pa pinata start default default
  player-monthly:
    '6':
    - rec purse add <player> 10000
    - crate key give <player> vote 2
    '12':
    - rec purse add <player> 12000
    - crate key give <player> vote 2
    '18':
    - rec purse add <player> 14000
    - give <player> netherite_ingot 1
    - recurrency give <player> 75 shards
    '24':
    - rec purse add <player> 16000
    - crate key give <player> fire 1
    '30':
    - rec purse add <player> 18000
    - crate key give <player> vote 3
    '36':
    - rec purse add <player> 20000
    - give <player> enchanted_golden_apple 1
    '42':
    - rec purse add <player> 22000
    - crate key give <player> fire 1
    - recurrency give <player> 150 shards
    '48':
    - rec purse add <player> 24000
    - crate key give <player> vote 3
    - give <player> netherite_ingot 1
    '54':
    - rec purse add <player> 26000
    - crate key give <player> fire 1
    '60':
    - rec purse add <player> 30000
    - crate key give <player> insane 1
    - give <player> enchanted_golden_apple 1
    '66':
    - rec purse add <player> 32000
    - crate key give <player> vote 4
    '72':
    - rec purse add <player> 36000
    - crate key give <player> fire 1
    - give <player> netherite_ingot 2
    - recurrency give <player> 300 shards
    '78':
    - rec purse add <player> 42000
    - give <player> enchanted_golden_apple 2
    '84':
    - rec purse add <player> 50000
    - crate key give <player> fire 2
    '90':
    - rec purse add <player> 70000
    - crate key give <player> insane 1
    - give <player> mace 1

rewards:
  vote:
  - rec purse add <player> 5000
  - crate key give <player> vote 1
  - recurrency give <player> 25 shards
  streak-monthly: []

monthly-draw:
  enabled: true
  min-votes: 1
  reward-command: lp user <player> parent addtemp arcano 30d
  auto-check-minutes: 5