name: vVotes
version: '${version}'
main: com.valerinsmp.vvotes.VVotesPlugin
api-version: '1.21'
authors: [ValerinSMP]
softdepend: [PlaceholderAPI, VotifierPlus]
commands:
  vote:
    description: Ayuda del sistema de votos.
    usage: /vote
    permission: vvotes.use
  votestats:
    description: Muestra tus estadisticas de votos.
    usage: /votestats
    permission: vvotes.use
  vvotes:
    description: Configuracion personal de anuncios de votos.
    usage: /vvotes toggle
    permission: vvotes.use
  vvotesadmin:
    description: Administracion de vVotes.
    usage: /vvotesadmin <help|about|reload|add|resetdaily|resetmonthly|adddaily|removedaily|addglobaldaily|removeglobaldaily|drawmonthly|drawhistory|topmonth>
    aliases: [voteadmin]
    permission: vvotes.admin
permissions:
  vvotes.use:
    default: true
  vvotes.admin:
    default: op
